### ISSUE TITLE
scHi-C

### ISSUE THREAD

**Issue by benxiahu** [MacoskoLab/liger#100]
Can I use Liger to analyze scHi-C data?
best,

**Comment by jw156605** [comment]
I haven't tried LIGER on Hi-C data. The challenge is how to process the Hi-C data (a matrix per cell) into gene-level measurements (a vector per cell). For example, you might determine, for each gene locus, whether it is in the A or B compartment. If you have a way to make gene-level scHi-C data, I'd be very interested to hear how the integration results look.
