### ISSUE TITLE
Problems with suggestK() and quantileAlignSNF()

### ISSUE THREAD

**Issue by zunwang95** [MacoskoLab/liger#103]
Hello,

I'm following the exact code in the "Walkthrough – Aligning PBMC Data" with the PBMC data your team provided. However,

1. When I tried to run:

`k.suggest <- suggestK(a.pbmc, num.cores = 4, gen.new = T, plot.log2 = F)`

It shows following:

    [1] "This operation may take several minutes depending on number of values being tested"
    [1] "Preprocessing for rep 1: optimizing initial factorization with largest test k=50"
    Converged in 4.707674 mins, 19 iterations.
    Best results with seed 1.
    [1] "Progress now represents completed factorizations (out of total number of k values)"

I think it means K value is larger than 50, but it should be 22 as said in Walkthrough, right?

2. Then when I tried to run:

`a.pbmc <- quantileAlignSNF(a.pbmc, resolution = 0.4, small.clust.thresh = 20)`

It shows following:

    [1] "Recomputing shared nearest factor space"
    [1] "Isolating small clusters with fewer than 20 members"
    [1] "making edge file."
    [1] "Starting SLM"
    Error in SLMCluster(edge = snf$out.summary, nstart = nstart, R = resolution,  :   
        127 exit status from java -jar C:/Users/GY/Documents/R/winlibrary/3.6/liger/java/ModularityOptimizer.jar edge3543701.txt 
    C:\Users\GY\AppData\Local\Temp\RtmpuqY1e4\louvain.out299461877b56.txt 1 0.4 1 10 10 1 0

Then the function stops and I cannot go further.

Could you please help me on these issues? thanks.

Best regards,

Zun Wang
Email: zwang32@tulane.edu

**Comment by vkozareva** [comment]
Hi Zun,
The messages from `suggestK` simply indicate which values it's testing (in this case, the highest k value it tests is 50). You have to look at the resulting plot to determine an appropriate k value for your datasets.

As for your second problem, it seems there's an issue running the underlying Java code for clustering. Do you have an appropriate version of Java installed on your machine (check our installation instructions)?

**Comment by yxaxaxa** [comment]
Hi,
I've encountered the same questions when using quantileAlignSNF in Rstudio to perform clustering, however when I put all these command on jupyter notebook, it all works fine, I have no idea what was going wrong , as I check the java -version ,it indicates that
 openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu 8.20.0.5-macosx) (build 1.8.0_121-b15)
OpenJDK 64-Bit Server VM (Zulu 8.20.0.5-macosx) (build 25.121-b15, mixed mode)
Anyone knows why it was happen

**Comment by Vivianstats** [comment]
I'm having a similar problem. Do you require a specific version of java?

**Comment by vkozareva** [comment]
We've confirmed that the following versions of Java work for liger: openjdk 1.8.0_222 (linux), java 1.6.0_65 (macos), java 1.8.0_181 (linux).

**Comment by apwjay** [comment]
I also receive "Error in SLMCluster(edge = snf$out.summary, nstart = nstart, R = resolution,  : 
  127 exit status from java -jar..." when running RunQuantileAlignSNF.  I am using Windows 10 with Java build 1.8.0_241-b07. Any suggestions on how to solve?
