### ISSUE TITLE
Regress out unwanted factors?

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [MacoskoLab/liger#113]
Hello, 
Using LIGER, I found some factors contributed by cycle cycle related genes and treatment, and I would like to regress out these unwanted factors. Does LIGER provide any functions to do that?

Thank you very much~

**Comment by jw156605** [comment]
This is one of the advantages of LIGER--technical signals often separate out into individual factors! All you need to do is omit the technical factors during the quantile normalization and clustering step.
For example, suppose that you ran `optimizeALS` with `k=20`. If factor 2 is cell cycle and factor 4 is treatment, you can remove the effects of these technical signals by running this command:
`quantileAlignSNF(liger_object,dims.use=c(1,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))`

**Comment by Hsu-Che-Wei** [comment]
Thanks, that's convenient.
But when I use the command:
quantileAlignSNF(ligerex, resolution = 0.5, small.clust.thresh = 20, dims.use = c(1,3,5,7,8,9,10,12,13,14,15,16,18,20))

There is this Error message:
Error in FUN(X[[i]], ...): Unable to normalize loadings for all cells; some cells loading on no selected factors.

Did I miss something?

**Comment by emacosko** [comment]
NMF is a sparse dimensionality reduction.  My suspicion is that you have some cells that only load on the factors not included in dims.use.  Therefore, they are a vector of zeros and have no information.  I would suggest removing those cells, or adding back dimensions.

**Comment by Hsu-Che-Wei** [comment]
Ummm...
Is there a way to detect those cells only load on the unwanted dimensions?
Or do you know where are the related information stored in liger object?

Thank you!

**Comment by jw156605** [comment]
Something like this should do the trick:
`use_these_factors = c(1,3,5,7,8,9,10,12,13,14,15,16,18,20)`
`cells.use = c(names(which(rowSums(liger_obj@H[[1]][use_these_factors]>0)>0)),names(which(rowSums(liger_obj@H[[2]][,use_these_factors]>0)>0)))`
`liger_obj = subsetLiger(liger_obj,cells.use = cells.use)`
`liger_obj = quantileAlignSNF(liger_obj,dims.use = use_these_factors)`

**Comment by Hsu-Che-Wei** [comment]
Amazing! it works.

Thanks.
