### ISSUE TITLE
error in function 'normalize'

### ISSUE THREAD

**Issue by BinDuan** [MacoskoLab/liger#115]
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘normalize’ for signature ‘"liger"’

**Comment by vkozareva** [comment]
It seems you might have installed the wrong version of liger -- did you install from github with `install_github('MacoskoLab/liger')`?

**Comment by z625715875** [comment]
I have the same issue too. I am sure the version of liger is right.

**Comment by MahdiMoradiMarjaneh** [comment]
I am getting this error too. `Liger` was installed with `install_github('MacoskoLab/liger')`

**Comment by MahdiMoradiMarjaneh** [comment]
I fixed this by using `::` to access the `normalize` function from the installed `Liger` package.

Example:
`ligerex = liger::normalize(ligerex)`

**Comment by jw156605** [comment]
There is a bioconductor package that also defines a normalize function. Under certain conditions, if you load that package first, it will overwrite the liger function.
