### ISSUE TITLE
suggestK issue

### ISSUE THREAD

**Issue by s18692001** [MacoskoLab/liger#116]
Hi there,
I'm following the tutorial and use suggestK function for my single cell methylation and RNA integration. When I use the command
`k.suggest <- suggestK(data, num.cores = 5, gen.new = T, return.data = T, plot.log2 = F,nrep = 5)`
It shows
`[1] "This operation may take several minutes depending on number of values being tested"
[1] "Preprocessing for rep 1: optimizing initial factorization with largest test k=50"
Error in optimizeALS.list(object = object@scale.data, k = k, lambda = lambda,  : 
  Select k lower than the number of cells in smallest dataset: 0`

Any suggestion?

**Comment by vkozareva** [comment]
It seems like one of your datasets has no cells in it -- you should check to make sure your liger object was created properly. If that's not the problem, could you give us a small reproducible example?

**Comment by strawberry789** [comment]
Hello,

I'm getting the same error:

Error in optimizeALS.list(object = object@scale.data, k = k, lambda = lambda, : Select k lower than the number of cells in smallest dataset: 0

But my Liger object shows 5984 cells in 2 datasets (scRNA+scATAC)

Thank you.
