### ISSUE TITLE
Seuratwrappers error

### ISSUE THREAD

**Issue by cnk113** [MacoskoLab/liger#120]
Hello,

I was following the Seurat wrapper vignette for my data, but when I was running RunOptimizeALS I got this error:

```Error: 'optimizeALS' is not an exported object from 'namespace:liger```
Any ideas why I am getting this error?

Thanks

**Comment by vkozareva** [comment]
Hello! Did you happen to try and install liger via CRAN with `install.packages`? Unfortunately there is another package called liger (and it's the one currently available through CRAN), and it doesn't have our functionality. If this is the case, you'll need to remove your current installation of liger and install our package with `devtools::install_github('MacoskoLab/liger')`.

**Comment by cnk113** [comment]
Ah I see, that solved the issue. Thanks.
