### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by xiaoxiasummer** [MacoskoLab/liger#126]
hello, developer
  i have some problem when i install the R package.
  when i use the command:
 library(devtools)
 install_github('MacoskoLab/liger')
 the Rtudio show such message:
 Downloading GitHub repo MacoskoLab/liger@master
These packages have more recent versions available.
Which would you like to update?

1: All                                 
2: CRAN packages only                  
3: None                                
4: rlang      (0.4.0  -> 0.4.1 ) [CRAN]
5: data.table (1.12.4 -> 1.12.6) [CRAN]

however whenever which number i choose, it still give me such error message:
package ‘digest’ successfully unpacked and MD5 sums checked
Error: Failed to install 'liger' from GitHub:
  Failed to install 'patchwork' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’

i am really do not know why? would you please give me some suggestion?

**Comment by vkozareva** [comment]
Have you tried installing the digest package separately before the liger installation? That might fix this issue.

**Comment by xiaoxiasummer** [comment]
thank you for your reply! i already installed the digest package. but It doesn't seem to work. 
Downloading GitHub repo MacoskoLab/liger@master
These packages have more recent versions available.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: Hmisc (4.2-0 -> 4.3-0) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
install.packages("devtools")
Enter one or more numbers, or an empty line to skip updates:
3
Downloading GitHub repo thomasp85/patchwork@master
Installing 1 packages: rlang
Installing package into ‘C:/Users/lenovo/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/3.6/rlang_0.4.1.zip'
Content type 'application/zip' length 1104134 bytes (1.1 MB)
downloaded 1.1 MB

package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'liger' from GitHub:
  Failed to install 'patchwork' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’
here is some error messages. which should i choose? would you please give me some suggestions?
