### ISSUE TITLE
Error in createLiger(pbmc.data) : could not find function "createLiger"

### ISSUE THREAD

**Issue by JPingLin** [MacoskoLab/liger#128]
Hi, 
I try to follow the walkthrough [tutorial](https://macoskolab.github.io/liger/walkthrough_pbmc.html). And I think the installation works, as I followed [this](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/) instruction and get the "Hello World!". But when I try to create Liger, it give me a error message. Other than library(liger) library(cowplot) What else should I load??

**Comment by JPingLin** [comment]
never mind, found need library(Matrix) library(patchwork). And it works now.

**Comment by page1one** [comment]
I also encountered this problem. I imported several packages of appeal, but there is still this error. Do you know what to do?
