### ISSUE TITLE
Cluster name F3 in the walkthrough

### ISSUE THREAD

**Issue by JPingLin** [MacoskoLab/liger#129]
Hi 
I am wondering is the Cluster name start with F something anything different from the rest of numbered cluster? In the walkthrough there is a F3, and in my analysis sometimes there is F49 or F15 etc. Can you give me some hint or where to check? 

Thanks!

**Comment by saisomesh2594** [comment]
Hey,

As far as I have understood, one would get clusters named as `F3`, `F49` , etc. when one does small cluster extraction in the `quantileAlignSNF` step where you set the `small.clust.thresh` parameter equal to the current `knn_k` or any other number except 0.
