### ISSUE TITLE
STARmap data imputation code missing

### ISSUE THREAD

**Issue by tabdelaal** [MacoskoLab/liger#132]
Hi,
I'm currently working on data integration between scRNAseq and spatial data, I want to test the performance of Liger to impute spatial genes. In the paper you mentioned how you did the imputation but I couldn't find the code for that. "We developed a simple method for predicting the spatial distributions of genes not measured in STARmap data. To do this, we simply compute a cross-dataset k-nearest neighbor graph in the aligned factor space. Then we set the value of each missing gene to the unweighted arithmetic mean of its k nearest neighbors in the other dataset. We used k = 50 for all analyses in the paper."

Can you share the code for this imputation? Thank you.

**Comment by vkozareva** [comment]
Hello! Have you tried using the `imputeKNN` function? It was created to capture this functionality. We can also publish a small walkthrough showing the usage of this function.

**Comment by tabdelaal** [comment]
Thank you for your reply. I tried the function and it's working well. 

Thanks again.
