### ISSUE TITLE
Error in RunOptimizeALS function 

### ISSUE THREAD

**Issue by Abghaith** [MacoskoLab/liger#134]
Hi, I get this error message when running this command ::
ifnb <- RunOptimizeALS(ifnb, k = 20, lambda = 5, split.by = "stim")
Erreur : 'optimizeALS' is not an exported object from 'namespace:liger'

**Comment by jw156605** [comment]
This looks like a problem with the SeuratWrappers package. Are both liger and seurat wrappers properly loaded?

**Comment by royfrancis** [comment]
I get the same error. I am sure that **liger** and **SeuratWrappers** packages are loaded.

```
>> packageVersion("liger")
[1] ‘1.1’
>> packageVersion("SeuratWrappers")
[1] ‘0.1.0’
```

**Comment by royfrancis** [comment]
The issue is that I installed `JEFworks/liger` rather than ` MacoskoLab/liger`.
