### ISSUE TITLE
,is this integration method suitable for data from different species on different platforms?

### ISSUE THREAD

**Issue by zhurenaibobi** [MacoskoLab/liger#135]
Dear all,
I have a question,is this integration method suitable for data from different species on different platforms?
Because my data comes from different species, one is a mouse(10X) and one is a dog(split-seq).
They are the same tissues：Olfactory bulb .
Thanks in advance.

yours,
limanman

**Comment by jw156605** [comment]
Yes, this is possible. In the LIGER paper, we used LIGER to integrate single-cell RNA-seq from mouse substantia nigra with single-nucleus RNA-seq from human substantia nigra. Obviously, this experimental design is less desirable than one in which data from both species come from the same platform.
