### ISSUE TITLE
issues re-analyzing subpopulations

### ISSUE THREAD

**Issue by pdesouza27** [MacoskoLab/liger#137]
I have 3 datasets from 3 glioblastoma patients in an object that's been through the entire pipeline. From correlating genes loaded on factors with the cluster assignments, it looks like tumor cells and immune cells have separated out nicely. I'd like to subset these subpopulations and re-run the factorization, but when I use optimizeSubset I get:

> optimizeSubset(gbm.liger.filter, cluster.subset = c(2,3,5,6,7,8,9,10,11,12,13))
Error in xj[i] : invalid subscript type 'list'

If I first use subsetLiger to isolate each population, I can rescale, perform factorization and run a dimension reduction. plotByDatasetandCluster returns an interesting plot. However, when I call plotGeneLoadings, I get:

> plotGeneLoadings(gbm.tumor.lambda50)
Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing

Any advice on how to debug is greatly appreciated!

**Comment by jw156605** [comment]
This function should be fixed now.
