### ISSUE TITLE
RANN.L1 dependency no longer on CRAN

### ISSUE THREAD

**Issue by ac3957** [MacoskoLab/liger#140]
When trying to install liger, there is a missing dependency RANN.L1
On its CRAN page:

> Package ‘RANN.L1’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the archive.
> 
> Archived on 2020-01-15 as nothing depends on it.

You'll want to either get this unarchived, or advise users to install RANN.L1 separately with:
`install_github("jefferis/RANN@master-L1")`

**Comment by skpalan** [comment]
Hi, thank you for your comment! We have noticed this dependency problem, it will be fixed very soon in the next version.

**Comment by htc502** [comment]
Hi, got the same error. any solution for this problem?

**Comment by ac3957** [comment]
as mentioned above,

`install_github("jefferis/RANN@master-L1")`

**Comment by raivivek** [comment]
Alternatively, you can also install though `conda`. `conda install r-rann.l1`.
