### ISSUE TITLE
Problems with seuratToLiger()

### ISSUE THREAD

**Issue by RegnerM2015** [MacoskoLab/liger#143]
Very cool and useful package! 

I am trying run LIGER on a fully processed combined Seurat object (after co-embedding, dim. reduction, etc.). I use seuratToLiger() to convert the combined Seurat object into a LIGER object. I split the combined object on "tech" (either ATAC or RNA). I renormalize and but use the variable features found by Seurat. 

`pbmc <- seuratToLiger(coembed, combined.seurat = T, meta.var = 'tech', 
renormalize = T, use.seurat.genes = T)`

However, when I scale but not center, it seems to remove quite a few genes between these two assays:

`pbmc <- scaleNotCenter(pbmc)
[1] "Removing 9432 genes not expressing in rna."
[1] "Removing 7866 genes not expressing in atac."`

And when I call optimizeALS(), it seems that my LIGER object has no cells.

`pbmc <- optimizeALS(pbmc, k=10,lambda = 5.0)
Error in optimizeALS.list(object = object@scale.data, k = k, lambda = lambda,  : 
  Select k lower than the number of cells in smallest dataset: 0`

What could be the issue here? I am using seuratToLiger() properly?

**Comment by MacoskoLab** [comment]
Could there be a discrepancy between the feature names in your RNA and ATAC assays? The fact that it's removing so many genes during that step seems to imply that there are many genes/features not shared.
