### ISSUE TITLE
help! I have some troubles when I install liger packages

### ISSUE THREAD

**Issue by lexie-lee** [MacoskoLab/liger#145]

**Comment by jw156605** [comment]
Have no fear, installation helps are here: https://github.com/MacoskoLab/liger

**Comment by lexie-lee** [comment]
when I tried using 'install_github('MacoskoLab/liger')',there will be a warn says'Failed to connect to api.github.com port 443: Connection refused',but I indeed open my VPN. I also tried down related packages, then use the command 'install.packages 'from my own Mac, this still didn't work. when there is no bug when I use command 'install_github',there will be long long long time waiting. there was a time I don't know why I can use the liger project, but when I close the window and open R studio another time, i can't use the package anymore. I have no idea about how to solve this problem.

**Comment by lexie-lee** [comment]
Hi, 
    I am here again cause I haven't solve my problem yet. I followed the steps in https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/.  and I can run the file 'helloworld.cpp' successfully, which means everything works appropriately, and then I use the command 'install_github('MacoskoLab/liger')' and my Rstudio will frozen...

**Comment by lexie-lee** [comment]
> Have no fear, installation helps are here: https://github.com/MacoskoLab/liger
