### ISSUE TITLE
installation of v0.5

### ISSUE THREAD

**Issue by orrzor** [MacoskoLab/liger#146]
Hi Josh and LIGER team,

Thanks for updating the algorithms. I tried installing the latest version (v0.5)
```
library(devtools)
install_github('MacoskoLab/liger', force = T)
```
After running this, the package version is still 0.4.2. Is there something else I should be doing? Thank you- Orr

**Comment by vkozareva** [comment]
We had a slight mix-up in our tagging/release, but we just updated the release to include the new functionality. If you try reinstalling now, it should install the correct version. Sorry about that!

**Comment by orrzor** [comment]
Thanks a lot Velina, that fixed it! Looking forward to liger'ing. -Orr
