### ISSUE TITLE
Error using Seurat Wrapper

### ISSUE THREAD

**Issue by ccruizm** [MacoskoLab/liger#150]
Good day,

I am having problems using the LIGER seurat wrapper with my dataset. After scaling the data, when I run RunOptimizeALS, I get the next message error:

```
|======================================================================| 100%
Converged in 1.780262 hours, 14 iterations.
Best results with seed 1.
Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
Traceback:

1. RunOptimizeALS(gbm, k = 20, lambda = 5, split.by = "orig.ident")
2. `colnames<-`(x = `*tmp*`, value = VariableFeatures(object = object))
```

Do you know where the error might be? Thanks in advance!

**Comment by skpalan** [comment]
This error suggests that the number of the variable features found by `Seurat` does not equal to the number of columns of the `W` matrix generated by `liger`. You might want to check if you have changed the number of the variable genes before running `optimizeALS`.
