### ISSUE TITLE
Liger installation on Windows

### ISSUE THREAD

**Issue by stefanonard85** [MacoskoLab/liger#154]
Hello, 

I am trying to install Liger on Windows machine. However after having installed all the packages required I get this error. Do you have any clue?
<img width="495" alt="Capture" src="https://user-images.githubusercontent.com/16965990/77959716-12467880-72a5-11ea-9ecf-235a9266258e.PNG">

**Comment by skpalan** [comment]
This error seems to be caused by the missing of package `RcppEigen`. Can you confirm the installation of it?

**Comment by stefanonard85** [comment]
Hello , 

you were right. Problem solved
Thx a lot.
