### ISSUE TITLE
Issues with makeFeatureMatrix

### ISSUE THREAD

**Issue by SaskiaFreytag** [MacoskoLab/liger#158]
Hi,

I have encountered several problems when trying to make a gene activity matrix from scATAC-seq data. When I tried to follow the instructions in your tutorial (https://macoskolab.github.io/liger/walkthrough_rna_atac.html), I did not get sensible results when sorting the fourth column of the fragments file. Instead I followed the instructions of the bedmap and sorted by location. Using this file I was able to obtain a file where the 6th column contains the barcodes. However when I try to put this into the makeFeatureMatrix function it seems to expect a different format. Would you be able to share with me the input format this function expects?

**Comment by lishashali** [comment]
I have the same problem

**Comment by lishashali** [comment]
I have the same problems. Did you solve this problem?

**Comment by skpalan** [comment]
Please refer to the newest tutorial [here](http://htmlpreview.github.io/?https://github.com/MacoskoLab/liger/blob/master/vignettes/Integrating_scRNA_and_scATAC_data.html), we have made some modifications on the `bedmap` commands. If it does not fix the problem, please provide the error message of `makeFeatureMatrix ` and your environment settings such as the output of `sessionInfo()`.
