### ISSUE TITLE
pre-processed data for scRNAseq and scATACseq integration vignette not available

### ISSUE THREAD

**Issue by emmagraham** [MacoskoLab/liger#168]
Hi, 

I am not able to access the pre-processed scRNAseq and scATACseq data for LIGER's [scRNAseq and scATACseq integration vignette](http://htmlpreview.github.io/?https://github.com/MacoskoLab/liger/blob/master/vignettes/Integrating_scRNA_and_scATAC_data.html). 

[This](https://umich.account.box.com/login?redirect_url=%2Ffolder%2F105861333378) link directs me to login to UMichigan's Box service. Is there a way to make this data accessible to everyone? 

Thank you in advance for your time!

**Comment by skpalan** [comment]
Sorry for the inconvenience. Can you try [this link](https://umich.box.com/s/wip2nzpktn6fdnlpc83o1u7anjn4ue2c) instead?

**Comment by emmagraham** [comment]
Thank you! Yes, this link works.
