### ISSUE TITLE
Feature Request: Plotting Warning Messages/Do Not Plot

### ISSUE THREAD

**Issue by samuel-marsh** [MacoskoLab/liger#171]
Hi,

Just thought I would post this here though feel free to close if this isn't something you are looking to do.
I think it would be beneficial if there was more consistent behavior/clear warnings from liger when attempting to plot features that don't exist in any of the datasets.

#### plotGene
For example if you attempt to plot a gene that doesn't exist (or spell wrong, etc) with plotGene you get what can seem to be a strange error message and no plot:
```
plotGene(object = liger, gene = "asdf")
Error in scale.factor * gene_vals_int : 
  non-numeric argument to binary operator
```
#### plotGeneViolin
However, attempting the same thing with plotGeneViolin actually does create a plot but all of the values are 0.  It will create plot regardless of whether what you type makes sense (see image).
```
plotGeneViolin(object = liger, gene = "asdf")
```
![liger_plot_example](https://user-images.githubusercontent.com/38284410/84260732-86dd3500-aae8-11ea-9097-64dd4b456d41.png)

It might be useful to implement something akin to what Seurat does in it's plotting functions:
```
# make sure features are present
  possible.features <- rownames(x = GetAssayData(object = object, slot = slot))
  if (any(!features %in% possible.features)) {
    bad.features <- features[!features %in% possible.features]
    features <- features[features %in% possible.features]
    if(length(x = features) == 0) {
      stop("No requested features found in the ", slot, " slot for the ", assay, " assay.")
    }
    warning("The following features were omitted as they were not found in the ", slot,
            " slot for the ", assay, " assay: ", paste(bad.features, collapse = ", "))
  }
```

Though from my understanding of liger object structure this may be slightly more complicated (or require new slot in the object) to compile consensus gene list for genes expressed across all datasets in the object.  But still a clearer message when attempting to plot genes not expressed would be great!

Best,
Sam

*edit*
This was all done using master branch v0.5.0 and R3.6.1.

**Comment by samuel-marsh** [comment]
Hi All,

Found another plotting error that I wanted to make you aware of.  Debated whether to open new issue or put here.  Please let me know if you'd rather this be new issue or leave here.

This issue I know is present in online branch and have not tested in master branch.  In this case I have liger object that is combination of 11 datasets.  I tried plotting one of the canonical microglia markers "CX3CR1" and got this error
```
> plotGene(obj, "CX3CR1", plot.by = "none")
Error in scale.factor * gene_vals_int : 
  non-numeric argument to binary operator
```

This seemed strange so I dug deeper.  The gene is present in data.  When I converted to Seurat object I had no issues plotting the gene.  However, when I told Seurat to split the plot by dataset what it revealed was that 2 of 11 of the datasets from the liger object did not any cells expressing the gene.

So something appears to be going wrong when a dataset doesn't express the gene.  This error is the same regardless of leaving the <plot.by> call in default by dataset state or changing it to <plot.by = "none"> as above.

Thanks,
Sam

**Comment by skpalan** [comment]
Hi Samuel, thanks for your comment. I just looked into this issue and did a quick fix. Can you give a try using the master branch again and see if it fixes the error you met?

**Comment by samuel-marsh** [comment]
Hi,

Yup, that works!  Thanks so much for quick fix.  Would it be possible to push that fix on the online branch as well, since I've been using that for most of my analysis?  If not I can always create custom function to import into workspace with the fix included but easier if it's just in the branch.

Thanks!!
Sam

**Comment by skpalan** [comment]
Hi, I just pushed the fix on the online branch as well. Enjoy!
