### ISSUE TITLE
Add drop = F when subsetting matrix

### ISSUE THREAD

**Issue by tkamath1** [MacoskoLab/liger#180]
Hope all is well liger team! I noticed a minor edge case when examining some publicly available snRNA-seq datasets that liger doesn't seem to address. Figured I'd make an issue instead of a PR because of the easiness of the fix.

For subsetting data, in the case when a dataset has only 1 cell, line 4840 (subsetLiger) in liger.R drops the attribute name of the dimension with a single value as per-dataset class converts from a matrix to a vector. To remedy can add "drop = F". So the line would be instead:

```object@raw.data[[q]][, cells, drop = F]```

**Comment by samuel-marsh** [comment]
Hey Tushar,

Just submitted PR that implements this change and another one if you want to close the issue.  See PR #191

**Comment by skpalan** [comment]
Hi, the PR made by sam has been merged but just for reminding, it doesn't make sense to create a sub-object that contains only 1 cell for the subsequent analyses such as iNMF. @tkamath1
