### ISSUE TITLE
Whether the data after integration could be used for DE analysis

### ISSUE THREAD

**Issue by Lyuzu** [MacoskoLab/liger#70]
Dear Developer,
I attempt to integrated several single-cell datasets which came from different timepoints and different people.
I tried Seurat 3.0 to integrated them and it didn't work well in my datasets, meanwhile the official tutorial of Seurat doesn't recommend users to do differential expression analysis by using the integrated expression matrix.  They recommend running differential expression tests on the “unintegrated” data because "The integration procedure inherently introduces dependencies between data points. This violates the assumptions of the statistical tests used for differential expression." 
My question is whether LIGER allows or recommends users doing DE tests on the integrated data. 
Thanks.

**Comment by jw156605** [comment]
LIGER does not modify the original gene expression matrix during integration. Thus, you can perform standard differential expression analysis to identify cell-type-specific differences between the datasets you're integrating. Alternatively, you can use the dataset-specific metagene loadings (V matrix) directly to identify DE genes.

**Comment by vkozareva** [comment]
The function `getFactorMarkers`, and visualization functions `plotWordClouds`, `plotGeneLoadings` are designed to help identify DE genes based on the dataset-specific factor loadings. Alternatively, you can apply DE tests of your choice on the raw data after assigning clusters -- converting to a Seurat object to use their DE test suite might help here.

**Comment by Lyuzu** [comment]
Thanks for the advice! I will try them. ( now stuck in the installation step)

**Comment by vkozareva** [comment]
What versions of R and Rstudio are you using? This may be related to this [issue](https://github.com/r-lib/devtools/issues/1939). One solution seems to be to set `Sys.setenv("TAR" = "internal")` before doing the install.

**Comment by Lyuzu** [comment]
> What versions of R and Rstudio are you using? This may be related to this [issue](https://github.com/r-lib/devtools/issues/1939). One solution seems to be to set `Sys.setenv("TAR" = "internal")` before doing the install.

Thanks for your advice. R version is 3.5.2 and Rstudio version is 1.1.463. The system of my computer is windows10. I have tried to use Docker by: 
`docker run -d -v /mypath/:/home/rstudio -p 8787:8787 docker.io/vkozareva/sc-liger:latest` 
It works smoothly. Next I could analyze my data. Thank you so much.

**Comment by vkozareva** [comment]
Great, I'll go ahead and close this then!
