### ISSUE TITLE
MarkerGenes with Cell types

### ISSUE THREAD

**Issue by Chatzinakos** [MacoskoLab/liger#76]
Dear Developer,

I have several (11) samples ( 10X Data) and i already figure out how to pass them to Liger. My question is if there is anyway to also give as annotation a list with marker genes with their corresponding cell cluster type (e.g     
CBLN2 | Ex1
ENC1 | Ex1
AC011288.2 | Ex1
PDZD2 | OPC
PDZRN4 | OPC
) 

and then plot them in the same map

Thanks

**Comment by vkozareva** [comment]
Do you mean plotting the expression of all of these markers on a multi-panel plot and then annotating the panels with the cell types? Unfortunately there's no way to do this natively in the package, but you could produce something like this with the following code (I've taken just three of your annotation pairs as examples):
```
plot_list <- list()
gene_list <- c('CBLN2', 'ENC1', 'PDZD2')
annot_list <- c('Ex1', 'Ex1', 'OPC')
for (i in 1:length(gene_list)) {
  p <- plotGene(liger_object, gene_list[i], return.plots = T)
  p <- lapply(p, function(x) {
    current <- x$labels$title
    x + ggtitle(paste(current, gene_list[i], '|', annot_list[i]))
  })
  plot_list <- c(plot_list, p)  
}
plot_grid(plotlist = plot_list, ncol = 11) # 11 for your 11 samples
```
