### ISSUE TITLE
Error when input datasets are a mix of normal matrices and dgCMatrix

### ISSUE THREAD

**Issue by NathanSkene** [MacoskoLab/liger#82]
Hi,

Firstly, this package is great, thanks for developing it!

I just ran it on a set of datasets, most of which were formatted as sparse matrices using Matrix::Matrix, but one had accidently been left as a conventional matrix. This went through initially processing fine, but threw a somewhat cryptic error during scaleNotCenter().

```
> a.pbmc <- scaleNotCenter(a.pbmc)
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing
```

Might be worth adding a check to ensure that all datasets are formatted as sparse matrices.

Thanks

**Comment by NathanSkene** [comment]
Sorry, spoke too soon there. Thought it was the mixed matrix thing that was the error, but that hasn't actually solved it.

**Comment by NathanSkene** [comment]
Found what it actually was. One of the datasets had a couple of rows which summed to zero. These get detected when createLiger is called, but they only get dropped from the dataset for which they are missing. One of these missing genes got included in the selection of variable genes. So they during scaleNotCenter there is this call:

> lapply(1:length(object@norm.data), function(i) {
>     scaleNotCenterFast(t(object@norm.data[[i]][object@var.genes, 
>         ]))
> })

That causes it to crash because that gene is missing. 

Proposed solution: during createLiger, if a gene is dropped from one dataset, drop it from all datasets

**Comment by vkozareva** [comment]
Thanks for pointing this out Nathan! 

We'll fix this behavior shortly, but in the meantime, there are a couple of workarounds you could use. If when you create your object, you set `take.gene.union = T`, the object will only drop the genes that aren't expressed in any of the datasets. Alternatively, you could set `combine = 'intersection'` when you run `selectGenes`, to keep only genes which were selected for all the datasets. 

These two options will of course have different effects on your downstream analyses, but hopefully one of them works for you for now!
