### ISSUE TITLE
How to determine the k value

### ISSUE THREAD

**Issue by newcounts** [MacoskoLab/liger#86]
Hello, I am trying to use liger to analyze 10X data, and I followed the walkthrough_pbmc documentation, but in the step of determining the k value, you suggest using the suggestK function to find the appropriate number of factors, and I used the function of suggestK, the result as follows:
![image](https://user-images.githubusercontent.com/45653892/61200021-b043e400-a712-11e9-8ea7-aa848643a4a8.png)
The data comes from walkthrough_pbmc, the recommended K value you give was 22, and I want to know how to find the best K value from this figure, thank you

**Comment by vkozareva** [comment]
In the PBMC walkthrough it actually specifies several non-default options with which to run `suggestK`, whereas this figure looks like it was produced with only the default options. I would recommend one change from the current walkthrough command, which is to run multiple iterations of NMF at each value of k by setting `nrep`; this might allow you to more easily identify an inflection point in the curve. For example, here is the result from running with the following options: 
```
k.suggest <- suggestK(a.pbmc, num.cores = 5, gen.new = T, return.data = T, plot.log2 = F, 
nrep = 5)
```
![image](https://user-images.githubusercontent.com/6119489/61890987-b1c19900-aed6-11e9-973d-55a7fd2847bc.png)

While this variation does take longer to run, I think it's more clear the inflection point is somewhere between k=15 and k=25. As the walkthrough states, we selected k=22 (after some inspection of downstream results), but you can try other values of k for similar results. For the supplementary figure in the paper, we set nrep=20 (though I would not recommend this for most analyses as it takes over an hour to run). We'll update the walkthrough with this recommended change; feel free to look at the [paper](https://www.ncbi.nlm.nih.gov/pubmed/31178122) supplement and methods for a more detailed explanation of this heuristic.
