### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by lc822** [MacoskoLab/liger#87]
Hi,

I am getting the following error when trying to install liger.  I am using macOS Mojave.

![image](https://user-images.githubusercontent.com/22564745/61307258-e7cf9080-a7e5-11e9-85e1-e3a03744b056.png)

Is there a way to overcome this?

Best wishes,
Lucy

**Comment by vkozareva** [comment]
This is because macOS's default compiler doesn't support openMP (right now required by RcppArmadillo). Have you tried following the recommended steps for installation on macOS (detailed [here](https://thecoatlessprofessor.com/programming/r-compiler-tools-for-rcpp-on-macos/))?

**Comment by lc822** [comment]
Thank you for the advice.  I have followed the installation guide and run the "quick check" at the end, which works fine, however I am still getting an error when trying to install liger.  

The error is now:

![image](https://user-images.githubusercontent.com/22564745/61402635-72d68680-a8cb-11e9-9260-c0b9cf7d74b2.png)

Is this a related error?

**Comment by MacoskoLab** [comment]
This has to do with Mojave -- did you make sure to follow the Mojave specific instructions for installing xcode CLI (found in a note on the post I referenced)? If that didn't work, can you see if any of the suggestions for installing xcode [here](https://github.com/RcppCore/Rcpp/issues/922) work for you?

**Comment by vkozareva** [comment]
This has to do with Mojave -- did you make sure to follow the Mojave specific instructions for installing xcode CLI (found in a note on the post I referenced)? If that didn't work, can you see if any of the suggestions for installing xcode here work for you?

**Comment by lc822** [comment]
Thank you - I have manage to fix this by reinstalling Command Line tools and running:

`sudo installer -pkg \
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg \
-target /`
