### ISSUE TITLE
Name conflicts with CRAN liger

### ISSUE THREAD

**Issue by hypercompetent** [MacoskoLab/liger#92]
Hi Macosco Lab team,

There's another package called liger on CRAN which is causing some issues for us with dependencies. If any other package has liger as a dependency, installation will force an overwrite of your version of liger with the CRAN version.

We ran into this problem because we were using your version of liger to run integration analysis, and installed a different package with CRAN liger as a dependency. This crashed the analysis pretty hard, and messed up a whole chain of dependencies.

It may be too late to change the name of this package, but it would be great to have some way to distinguish this package from the CRAN liger. Does your team (or any other reader) know of a way to pull these apart?

Thanks!
-Lucas

**Comment by vkozareva** [comment]
We're definitely aware of this name conflict, though as you may have seen online, there aren't many great solutions outside of renaming our package. We're currently preparing the package for submission to CRAN (which will involve at least a CRAN-facing name change). Depending on the extent of the change, there might still be a conflict with the other liger package. 

If you need to use both for your analysis, I would suggest trying to use [packrat](https://rstudio.github.io/packrat/) to keep your analysis steps (and their respective dependencies) in isolated projects, while ferrying your data between them in an intermediate state. Not a perfect solution, but hopefully workable for you!

**Comment by lianos** [comment]
As an aside, for the internet traveler that lands here from google: [renv](https://rstudio.github.io/renv/) is the solution Rstudio is pushing going forward as the "lessons learned from packrat" package in order to keep track of and isolate dependencies to help create reproducible workflows (and dev environments, and so on ...)
