### ISSUE TITLE
Java sources are not included

### ISSUE THREAD

**Issue by rekado** [MacoskoLab/liger#96]
Hi,

I was just about to package liger for GNU Guix and noticed that there is no source code for the installed Jar.  Could you please point me to the Java sources or, better yet, include them in this repository?

In Guix we build everything completely from source and in a reproducible fashion, so I can't just include a pre-built archive.

Thanks!

**Comment by vkozareva** [comment]
The Java source code can be found near the bottom of this [post](http://www.ludowaltman.nl/slm/) (by the original authors) as a compressed archive. We'll include the source code in our next update!

**Comment by rekado** [comment]
Thanks.  There is no license declaration for the Java sources, but I contacted the authors who told me that the Java sources are released under the terms of the Expat/MIT license.
