### ISSUE TITLE
scRNAseq + scDNAme integration vignette

### ISSUE THREAD

**Issue by Kcjohnson** [MacoskoLab/liger#99]
Thanks for generating this helpful tool! After reading the paper and its methods (specifically related to Fig. 6 and 7), I was hoping to find a vignette for defining cell types using both single cell RNAseq and DNA methylation. Are there plans to make such a vignette or code from the sections related to paper's Fig. 6-7 available?

**Comment by jw156605** [comment]
Sure, I'll put together a short vignette. Basically the only steps that we did differently from the RNA analysis were (1) obtaining features correlated with gene expression by inverting the direction of the methylation values, and (2) performing gene selection in a slightly different fashion.

**Comment by Kcjohnson** [comment]
Thank you for the pointers and putting together the quick vignette. It's great to have an explicit example.

**Comment by s18692001** [comment]
Hi there, sorry I don't see the corresponding vignette for integration of RNA and methylation. Could you let me know where it is? Thanks!

**Comment by jw156605** [comment]
I just posted a vignette showing how to jointly define cell types from RNA and DNA methylation. Feel free to follow up if you have additional questions.
